server:
  port: 8080
spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: http://localhost:8081/
          predicates:
            - Path=/products/**
        - id: carts
          uri: http://localhost:8082/
          predicates:
            - Path=/carts/**
        - id: counter
          uri: http://localhost:8083/
          predicates:
            - Path=/counter/**
        - id: api
          uri: http://localhost:8084/
          predicates:
            - Path=/api/**
        - id: orders
          uri: http://localhost:8085/
          predicates:
            - Path=/orders/**
        - id: delivery
          uri: http://localhost:8086/
          predicates:
            - Path=/delivery/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
