spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin
  application:
    name: poscarts
server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: ${spring.application.name}
    prefer-ip-address: true
