spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin
  application:
    name: posorders
  rabbitmq:
    host: localhost # rabbitmq docker ip
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      bindings:
        output:
          destination: delivery
          contentType: application/json

server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: ${spring.application.name}
    prefer-ip-address: true
