spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin
  application:
    name: posapi
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    #hostname: ${spring.application.name}
    prefer-ip-address: true
